# Конфигурация детектора заставок
frames_per_second: 2    # Частота кадров для обработки
batch_size: 32          # Размер батча для извлечения признаков
similarity_threshold: 0.82 # Порог схожести кадров
min_intro_length: 3     # Минимальная длина заставки (сек)
max_intro_length: 30    # Максимальная длина заставки (сек)
cleanup: true           # Удалять временные файлы после обработки